name: login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.11
  google_sign_in: ^6.2.1 
  intl: ^0.19.0
  flutter_native_splash: ^2.4.1
  rflutter_alert: ^2.0.7
  flutter_intro: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
   - family: CM Sans Serif
     fonts:
       - asset: assets/fonts/cm_sans_serif_2012.ttf